# Generated by Django 3.0.8 on 2020-08-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='post_title', max_length=50),
        ),
    ]
