# Generated by Django 3.0.8 on 2020-08-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location_information',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='time_information',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
