# Generated by Django 3.0.8 on 2020-08-23 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_city_state'),
        ('posts', '0009_auto_20200823_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cities.State'),
        ),
    ]
