# Generated by Django 3.0.8 on 2020-08-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20200826_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_of_downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='num_of_upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
