# Generated by Django 3.0.8 on 2020-08-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_upvotes'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upvoted_posts',
            field=models.ManyToManyField(related_name='users_who_upvoted', to='posts.Post'),
        ),
    ]
