# Generated by Django 3.0.8 on 2020-08-25 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_upvoted_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='upvoted_posts',
        ),
    ]
