# Generated by Django 3.0.8 on 2020-08-25 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('posts', '0012_post_upvotes'),
        ('accounts', '0005_auto_20200825_0151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
