# Generated by Django 3.0.8 on 2020-08-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200825_0334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
