# Generated by Django 3.0.8 on 2020-08-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200825_0942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
