# Generated by Django 3.0.8 on 2020-08-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_city_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
